version: '3.8'

services:
  # Trpkit applications (mainly used for qa and production)
  web-client:
    build:
      context: .
      dockerfile: apps/web-client/Dockerfile
    ports:
      - "3001:3000"
    profiles:
      - fullstack
      - production

  marketing:
    build:
      context: .
      dockerfile: apps/marketing/Dockerfile
    ports:
      - "3002:3000"
    profiles:
      - fullstack
      - production

  urlshortener:
    build:
      context: .
      dockerfile: apps/url-shortener/Dockerfile
    ports:
      - "8888:8888"
    profiles:
      - fullstack
      - production

  # Third-party applications (mainly used for dev)
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: trpkit
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    profiles:
      - development
      - fullstack

  inbucket:
    image: inbucket/inbucket:latest
    ports:
      - "9000:9000"
      - "2500:2500"
      - "1100:1100"
    profiles:
      - development
      - fullstack